services:
  - type: web
    name: krishidrishti-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python train_crop.py --csv crop_recommendation.csv
    startCommand: python start.py
    envVars:
      - key: LLM_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PLANTNET_API_KEY
        sync: false
    healthCheckPath: /health
