"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "hi" | "pa" | "te" | "gu";

export const translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    cropDiagnosis: "Crop Diagnosis",
    cropRecommendation: "Crop Recommendation",
    smartIrrigation: "Smart Irrigation",
    weatherIntelligence: "Weather Intelligence",
    sustainabilityScore: "Sustainability Score",
    farmMonitoring: "Farm Monitoring (IoT)",
    aiAssistant: "AI Farmer Assistant",
    farmAdvisor: "Farm Advisor",
    settings: "Settings",

    // Badges & Common Header
    activeStation: "Active Station",
    quickDiagnosis: "Quick Diagnosis",
    stationName: "Northern Agri-Hub (Haryana)",
    plotInfo: "Plot A (Karnal Hub)",
    plotDetails: "4.2 Hectares • Drip Active",
    smartAgri: "Smart Agriculture",
    simulationMode: "Simulation Mode",
    coreAi: "Core AI",
    agentic: "Agentic",

    // Smart Irrigation Page
    irrigationTitle: "Smart Irrigation & Soil Hydration",
    irrigationDesc: "Sensor-driven root zone moisture telemetry, evapotranspiration modeling, and weather-synchronized watering schedules.",
    manualCycle: "Manual Cycle Override",
    haltSolenoid: "Halt Active Solenoid",
    rootZoneMoisture: "Root Zone Moisture",
    target: "Target",
    waterRequired: "Water Required",
    fieldCapacity: "To achieve field capacity",
    nextCycle: "Next Cycle",
    eveningDrip: "Evening drip irrigation slot",
    valveStatus: "Valve Status",
    valveRunning: "Running (Drip)",
    valveStandby: "Standby",
    soilMoistureGauge: "Soil Moisture Gauge",
    capacitiveDepth: "Capacitive probe telemetry at 20cm depth",
    volumetricContent: "Volumetric Water Content",
    underMoistureTitle: "Under Recommended Moisture",
    underMoistureDesc: "Soil moisture is 7% below lower comfort threshold. Irrigation is advised before nighttime transpiration.",
    moistureTrendTitle: "24-Hour Soil Moisture Trend",
    moistureTrendDesc: "Hourly probe readings vs permanent wilting point",
    moisturePercent: "Moisture %",
    targetMin: "Target Minimum (45%)",

    // Recommendations Page
    recTitle: "Intelligent Crop Recommendation",
    recDesc: "Input soil chemistry parameters and microclimate conditions to receive AI-ranked crop varieties optimized for yield, water-efficiency, and soil rejuvenation.",
    soilParamsTitle: "Soil & Climate Parameters",
    soilType: "Soil Type",
    loamySoil: "Loamy Soil (Balanced)",
    clayeyLoam: "Clayey Loam (High Moisture Retention)",
    sandyLoam: "Sandy Loam (Rapid Drainage)",
    blackCotton: "Black Cotton Soil (High Clay Content)",
    nitrogen: "Nitrogen (N)",
    phosphorus: "Phosphorus (P)",
    potassium: "Potassium (K)",
    soilPh: "Soil pH",
    temp: "Temp (°C)",
    humidity: "Humidity (%)",
    rainfall: "Rainfall (mm)",
    calcBtn: "Calculate Recommended Crops",
    evaluatingBtn: "Evaluating Agronomic Match...",
    awaitingTitle: "Awaiting Soil & Microclimate Evaluation",
    awaitingDesc: "Adjust your farm's NPK values and climate estimates on the left and click \"Calculate Recommended Crops\" to view ranked suitability scores.",
    projectedYield: "Projected Yield",
    suitability: "Suitability",
    waterReq: "Water",
    growthCycle: "Cycle",
    days: "Days",
    sustainabilityRating: "Sustainability",

    // Diagnosis Page
    diagnosisTitle: "AI Crop Disease Detection",
    diagnosisDesc: "Upload leaf imagery for computer vision diagnostic analysis, severity grading, and actionable agronomic protocols.",
    diagnosisHistory: "Diagnosis History",
    scanLeafBtn: "Scan Crop Leaf",

    // Dashboard Page
    dashboardTitle: "Karnal Precision Agro-Hub",
    dashboardDesc: "Operational synthesis across crop pathology, root zone hydrology, microclimate indices, and agentic briefings.",
    overallCropHealth: "Overall Crop Health",
    foliageIntegrity: "Plot A foliage integrity",
    activeDiseaseAlerts: "Active Disease Alerts",

    // Settings Page
    settingsTitle: "Farm Preferences & Configuration",
    settingsDesc: "Manage land geometry, localized agro-climatic region, unit standards, and multilingual delivery.",
    farmerProfile: "Farmer & Plot Profile",
    farmerName: "Farmer Name",
    contactPhone: "Contact Phone",
    farmHolding: "Farm / Holding Name",
    locationCoords: "Location Coordinates",
    multilingual: "Multilingual & Unit Localization",
    appLanguage: "Application Language",
    areaUnits: "Area Units",
    realtimeAlerts: "Real-time Agro Alerts",
    diseaseAlerts: "Critical Crop Disease Alerts",
    diseaseAlertsDesc: "Instant alerts when neighboring plots or weather triggers fungal sporulation warnings.",
    weatherAlerts: "Precipitation & Frost Warnings",
    weatherAlertsDesc: "Advise postponement of scheduled irrigation or chemical foliar sprays.",
    saveSettings: "Save Farm Settings",
    savingSettings: "Saving Preferences...",
    savedSuccess: "Saved Successfully!",
    settingsPersisted: "Settings saved and persisted locally.",

    // Quick Actions / Prompts
    analyzeCrop: "Analyze Your Crop",
    explorePlatform: "Explore KrishiDrishti",

    // Dashboard
    scanCropLeaf: "Scan Crop Leaf",
    recentFoliageInspections: "Recent Foliage Inspections",
    fullAuditHistory: "Full Audit History",
    todaysBriefing: "Today's Agentic Operational Briefing",
    viewAllSignals: "View All Signals",
    microclimatRisk: "Microclimate Risk",
    fullRadar: "Full Radar",
    currentTemp: "Current Temp",
    airHumidity: "Air Humidity",
    pathogenRisk: "Pathogen Risk",
    soilMoisture: "Soil Moisture",
    sustainabilityRating2: "Sustainability Rating",

    // Diagnosis
    coreModule: "Core Module",

    // Irrigation
    irrigationIntelligence: "Smart Irrigation Intelligence",
    irrigationIntelligenceDesc: "Precision soil moisture management with real-time sensor telemetry and rain-aware scheduling.",
    cropGrowthStage: "Crop Growth Stage",
    stageThresholdNote: "threshold changes based on stage",
    rainDeferNotice: "mm of rain forecast in the next 24 hours — irrigation has been automatically deferred.",
    belowThreshold: "Below threshold",
    moistureOptimal: "Moisture optimal",
    moistureTrend: "Moisture Trend",
    lastReadings: "Last 6 sensor readings · 10 min intervals",
    refresh: "Refresh",

    // Weather
    weatherTitle: "Agro-Weather Intelligence & Disease Risk",
    weatherDesc: "Microclimate forecasting tailored to crop pathogen dynamics, spore development, and evapotranspiration rates.",
    detectingLocation: "Detecting location...",
    useMyLocation: "Use My Location",
    temperature: "Temperature",
    relativeHumidity: "Relative Humidity",
    precipitation: "Precipitation",
    next24h: "Next 24 hours",
    pathogenRiskIndex: "Pathogen Risk Index",
    fungalPressure: "Fungal Pressure",
    agronomicAdvisories: "Agronomic Weather Advisories",
    fiveDayOutlook: "5-Day Microclimate Outlook & Rain Probability",
    locationDenied: "Location access was denied. Showing weather for default location (Karnal, Haryana). Click \"Use My Location\" to use your actual location.",

    // Sustainability
    sustainabilityTitle: "Farm Sustainability & ESG Indices",
    sustainabilityDesc: "Enter your actual resource usage to compute a live sustainability score from the backend engine.",
    resourceUsageInputs: "Resource Usage Inputs",
    waterUsed: "Water Used (Liters)",
    optimalWater: "Optimal Water (Liters)",
    fertilizerUsed: "Fertilizer Used (kg)",
    recommendedDose: "Recommended Dose (kg)",
    cropHealthLive: "Crop health is fetched live from the IoT sensor feed.",
    calculateScore: "Calculate Score",
    calculating: "Calculating...",
    awaitingInputTitle: "Awaiting Input",
    awaitingInputDesc: "Enter your water and fertilizer usage on the left, then click Calculate Score.",
    overallEcoRating: "Overall Ecological Farm Rating",
    waterSaved: "Water Saved",
    carbonOffset: "Carbon Offset Est.",
    vsYourUsage: "vs Your Usage",
    co2Equivalent: "CO₂ Equivalent",

    // Monitoring
    monitoringTitle: "IoT Sensor Telemetry & Field Nodes",
    monitoringDesc: "Live telemetry from LoRaWAN field probes, soil capacitive sensors, and canopy weather nodes.",
    simulatedSensors: "Simulated Sensors",
    hardwareGateway: "Hardware LoRa Gateway",
    multiSensorTelemetry: "Multi-Sensor Telemetry Over Time",
    telemetryDesc: "Temperature, relative humidity, and moisture correlation",

    // Advisor
    advisorTitle: "Agentic Agricultural Advisor",
    advisorDesc: "Autonomous reasoning engine synthesizing multi-modal signals: leaf pathology, radar precipitation, sensor hydrology, and crop market windows.",
    todaysFarmBriefing: "Today's Farm Briefing (06:00 AM Synthesis)",
    rankedRecommendations: "Ranked Operational Recommendations",
    recommendedAction: "Recommended Action:",
    signalInputs: "Signal Inputs",
    impact: "Impact",
    acknowledgeAction: "Acknowledge Action",
    acknowledged: "Acknowledged",
    priority: "Priority",

    // Model Metrics Page
    modelMetricsTitle: "Model Evaluation Metrics",
    modelMetricsDesc: "Training diagnostics for the core crop disease detection model trained on PlantVillage dataset.",
    modelArchitecture: "Model Architecture",
    dataset: "Dataset",
    totalImages: "Total Images",
    finalValAccuracy: "Final Val Accuracy",
    trainingConfig: "Training Configuration",
    lossTab: "Loss",
    f1Tab: "Macro-F1",
    confusionTab: "Confusion",
    perClassTab: "Per-Class",

    // Landing Page
    landingHeroBadge: "AI-Powered Intelligent Agriculture Platform",
    landingHeroTitle: "Intelligent Crop Health & Smart Agriculture",
    landingHeroDesc: "KrishiDrishti combines deep learning computer vision, IoT soil hydrology, agro-weather microclimate models, and agentic farm advising into one unified agricultural intelligence ecosystem.",
    landingGetStarted: "Get Started Free",
    landingSignIn: "Sign In",
    landingGoToDashboard: "Go to Dashboard",
    landingExploreModule: "Explore Module",
    landingFeaturesTitle: "Complete Agricultural Intelligence Ecosystem",
    landingFeaturesDesc: "Modular agricultural intelligence platform with pluggable FastAPI backend contracts and responsive edge design.",
    landingCtaTitle: "Ready to Empower Agricultural Productivity?",
    landingCtaDesc: "Test our trained computer vision leaf pathology model or explore the multi-modal agentic agricultural briefing.",
    landingCreateAccount: "Create Free Account",
    landingFooterTagline: "Empowering Farmers with Artificial Intelligence",
    landingBackToTop: "Back to Top",
    landingIntelligentCrop: "Intelligent Crop Health Platform",

    // Advisor fallback
    advisorFallbackDesc: "The reasoning engine is synthesizing multi-modal signals from your farm sensors, weather forecast, and crop diagnosis history.",

    // Sidebar
    modelMetricsNav: "Model Metrics",
  },
  hi: {
    // Navigation
    dashboard: "डैशबोर्ड",
    cropDiagnosis: "फसल रोग निदान",
    cropRecommendation: "फसल सिफारिश",
    smartIrrigation: "स्मार्ट सिंचाई",
    weatherIntelligence: "मौसम पूर्वानुमान",
    sustainabilityScore: "सतत कृषि स्कोर",
    farmMonitoring: "खेत निगरानी (IoT)",
    aiAssistant: "एआई किसान सहायक",
    farmAdvisor: "कृषि सलाहकार",
    settings: "सेटिंग्स",

    // Badges & Common Header
    activeStation: "सक्रिय केंद्र",
    quickDiagnosis: "त्वरित जांच",
    stationName: "उत्तरी कृषि केंद्र (हरियाणा)",
    plotInfo: "खेत A (करनाल हब)",
    plotDetails: "4.2 हेक्टेयर • ड्रिप सिंचाई सक्रिय",
    smartAgri: "स्मार्ट कृषि",
    simulationMode: "सिमुलेशन मोड",
    coreAi: "मुख्य एआई",
    agentic: "स्वायत्त एजेंट",

    // Smart Irrigation Page
    irrigationTitle: "स्मार्ट सिंचाई एवं मृदा जल प्रबंधन",
    irrigationDesc: "सेंसर-आधारित जड़ क्षेत्र नमी टेलीमेट्री, वाष्पोत्सर्जन मॉडलिंग और मौसम-अनुकूलित सिंचाई कार्यक्रम।",
    manualCycle: "मैन्युअल सिंचाई चक्र चालू करें",
    haltSolenoid: "सक्रिय सोलेनोइड रोकें",
    rootZoneMoisture: "जड़ क्षेत्र में नमी",
    target: "लक्ष्य",
    waterRequired: "आवश्यक जल मात्रा",
    fieldCapacity: "खेत की क्षमता तक लाने हेतु",
    nextCycle: "अगला चक्र",
    eveningDrip: "शाम का ड्रिप सिंचाई समय",
    valveStatus: "वाल्व की स्थिति",
    valveRunning: "चालू (ड्रिप सिंचाई)",
    valveStandby: "स्टैंडबाय (प्रतीक्षारत)",
    soilMoistureGauge: "मृदा नमी मीटर (गेज)",
    capacitiveDepth: "20 सेमी गहराई पर कैपेसिटिव जांच टेलीमेट्री",
    volumetricContent: "आयतनिक जल मात्रा",
    underMoistureTitle: "अनुशंसित सीमा से कम नमी",
    underMoistureDesc: "मिट्टी की नमी अनुशंसित न्यूनतम स्तर से 7% कम है। रात के वाष्पोत्सर्जन से पूर्व सिंचाई की सलाह दी जाती है।",
    moistureTrendTitle: "24 घंटे का मृदा नमी रुझान",
    moistureTrendDesc: "प्रति घंटा सेंसर रीडिंग बनाम न्यूनतम मुरझाने का बिंदु",
    moisturePercent: "नमी %",
    targetMin: "न्यूनतम लक्ष्य (45%)",

    // Recommendations Page
    recTitle: "बुद्धिमान फसल सिफारिश प्रणाली",
    recDesc: "मिट्टी के पोषक तत्वों और सूक्ष्म-जलवायु स्थिति दर्ज करें और पैदावार, जल-बचत तथा मिट्टी सुधार के आधार पर एआई-अनुशंसित फसलें प्राप्त करें।",
    soilParamsTitle: "मिट्टी एवं जलवायु मापदंड",
    soilType: "मिट्टी का प्रकार",
    loamySoil: "दोमट मिट्टी (संतुलित)",
    clayeyLoam: "चिकनी दोमट (अधिक नमी रोकने वाली)",
    sandyLoam: "बलुई दोमट (तेज़ जल निकासी)",
    blackCotton: "काली कपास मिट्टी (उच्च चिकनी सामग्री)",
    nitrogen: "नाइट्रोजन (N)",
    phosphorus: "फास्फोरस (P)",
    potassium: "पोटेशियम (K)",
    soilPh: "मिट्टी का pH",
    temp: "तापमान (°C)",
    humidity: "नमी (%)",
    rainfall: "वर्षा (मिमी)",
    calcBtn: "अनुशंसित फसलों की गणना करें",
    evaluatingBtn: "कृषि डेटा का मिलान किया जा रहा है...",
    awaitingTitle: "मिट्टी एवं जलवायु मूल्यांकन की प्रतीक्षा है",
    awaitingDesc: "बाईं ओर अपनी मिट्टी के NPK मान और जलवायु अनुमान सेट करें और उपयुक्त फसलें देखने के लिए 'अनुशंसित फसलों की गणना करें' पर क्लिक करें।",
    projectedYield: "अनुमानित पैदावार",
    suitability: "उपयुक्तता",
    waterReq: "पानी की आवश्यकता",
    growthCycle: "अवधि",
    days: "दिन",
    sustainabilityRating: "स्थिरता रेटिंग",

    // Diagnosis Page
    diagnosisTitle: "एआई फसल रोग पहचान एवं निदान",
    diagnosisDesc: "पत्ती की तस्वीर अपलोड करें और कंप्यूटर विज़न द्वारा रोग की पहचान, गंभीरता और सटीक उपचार पाएँ।",
    diagnosisHistory: "निदान इतिहास",
    scanLeafBtn: "पत्ती स्कैन करें",

    // Dashboard Page
    dashboardTitle: "करनाल प्रिसिजन एग्रो-हब",
    dashboardDesc: "फसल रोग, जड़ नमी जल विज्ञान, मौसम सूचकांक और कृषि सलाह का समग्र विश्लेषण।",
    overallCropHealth: "समग्र फसल स्वास्थ्य",
    foliageIntegrity: "खेत A की पत्ती अखंडता",
    activeDiseaseAlerts: "सक्रिय रोग अलर्ट",

    // Settings Page
    settingsTitle: "फार्म प्राथमिकताएं एवं विन्यास",
    settingsDesc: "खेत का क्षेत्रफल, स्थानीय जलवायु क्षेत्र, मापक इकाइयां और बहुभाषी भाषा प्रबंधित करें।",
    farmerProfile: "किसान एवं खेत का विवरण",
    farmerName: "किसान का नाम",
    contactPhone: "संपर्क फोन नंबर",
    farmHolding: "खेत / जोत का नाम",
    locationCoords: "स्थान / निर्देशांक",
    multilingual: "बहुभाषी एवं क्षेत्रीय मानक",
    appLanguage: "एप्लिकेशन भाषा",
    areaUnits: "क्षेत्रफल की इकाई",
    realtimeAlerts: "रीयल-टाइम कृषि अलर्ट",
    diseaseAlerts: "गंभीर फसल रोग चेतावनी",
    diseaseAlertsDesc: "मौसम या पड़ोसी खेतों में संक्रमण का जोखिम बढ़ने पर तुरंत चेतावनी।",
    weatherAlerts: "वर्षा एवं पाला चेतावनी",
    weatherAlertsDesc: "अनुसूचित सिंचाई या कीटनाशक छिड़काव स्थगित करने की सलाह।",
    saveSettings: "फार्म सेटिंग्स सहेजें",
    savingSettings: "सेटिंग्स सहेजी जा रही हैं...",
    savedSuccess: "सफलतापूर्वक सहेजा गया!",
    settingsPersisted: "सेटिंग्स सुरक्षित रूप से सहेजी गईं।",

    // Quick Actions / Prompts
    analyzeCrop: "फसल की जांच करें",
    explorePlatform: "कृषि दृष्टि देखें",

    // Dashboard
    scanCropLeaf: "पत्ती स्कैन करें",
    recentFoliageInspections: "हालिया पत्ती जांच",
    fullAuditHistory: "पूरा इतिहास",
    todaysBriefing: "आज की कृषि सलाह",
    viewAllSignals: "सभी संकेत देखें",
    microclimatRisk: "सूक्ष्म जलवायु जोखिम",
    fullRadar: "पूरा रेडार",
    currentTemp: "वर्तमान तापमान",
    airHumidity: "वायु नमी",
    pathogenRisk: "रोगाणु जोखिम",
    soilMoisture: "मिट्टी नमी",
    sustainabilityRating2: "स्थिरता रेटिंग",

    // Diagnosis
    coreModule: "मुख्य मॉड्यूल",

    // Irrigation
    irrigationIntelligence: "स्मार्ट सिंचाई प्रणाली",
    irrigationIntelligenceDesc: "रीयल-टाइम सेंसर डेटा और मौसम-सचेत शेड्यूलिंग के साथ सटीक मृदा नमी प्रबंधन।",
    cropGrowthStage: "फसल विकास चरण",
    stageThresholdNote: "चरण के अनुसार सीमा बदलती है",
    rainDeferNotice: "मिमी बारिश का पूर्वानुमान — सिंचाई स्वचालित रूप से स्थगित की गई।",
    belowThreshold: "सीमा से नीचे",
    moistureOptimal: "नमी उचित",
    moistureTrend: "नमी रुझान",
    lastReadings: "अंतिम 6 सेंसर रीडिंग · 10 मिनट अंतराल",
    refresh: "ताजा करें",

    // Weather
    weatherTitle: "कृषि मौसम विज्ञान और रोग जोखिम",
    weatherDesc: "फसल रोगाणु गतिशीलता, बीजाणु विकास और वाष्पोत्सर्जन दर के अनुसार सूक्ष्म जलवायु पूर्वानुमान।",
    detectingLocation: "स्थान खोजा जा रहा है...",
    useMyLocation: "मेरा स्थान उपयोग करें",
    temperature: "तापमान",
    relativeHumidity: "सापेक्ष नमी",
    precipitation: "वर्षा",
    next24h: "अगले 24 घंटे",
    pathogenRiskIndex: "रोगाणु जोखिम सूचकांक",
    fungalPressure: "फंगल दबाव",
    agronomicAdvisories: "कृषि मौसम सलाह",
    fiveDayOutlook: "5-दिनीय मौसम और वर्षा संभावना",
    locationDenied: "स्थान अनुमति अस्वीकार की गई। डिफ़ॉल्ट स्थान (करनाल, हरियाणा) का मौसम दिखाया जा रहा है।",

    // Sustainability
    sustainabilityTitle: "खेत स्थिरता और ESG सूचकांक",
    sustainabilityDesc: "वास्तविक संसाधन उपयोग दर्ज करें और लाइव स्थिरता स्कोर प्राप्त करें।",
    resourceUsageInputs: "संसाधन उपयोग इनपुट",
    waterUsed: "उपयोग किया पानी (लीटर)",
    optimalWater: "इष्टतम पानी (लीटर)",
    fertilizerUsed: "उपयोग किया खाद (kg)",
    recommendedDose: "अनुशंसित मात्रा (kg)",
    cropHealthLive: "फसल स्वास्थ्य IoT सेंसर से लाइव लिया जाता है।",
    calculateScore: "स्कोर गणना करें",
    calculating: "गणना हो रही है...",
    awaitingInputTitle: "इनपुट की प्रतीक्षा",
    awaitingInputDesc: "बाएं ओर पानी और खाद का उपयोग दर्ज करें, फिर स्कोर गणना करें पर क्लिक करें।",
    overallEcoRating: "समग्र पारिस्थितिक खेत रेटिंग",
    waterSaved: "बचाया पानी",
    carbonOffset: "कार्बन ऑफसेट अनुमान",
    vsYourUsage: "आपके उपयोग से",
    co2Equivalent: "CO₂ समतुल्य",

    // Monitoring
    monitoringTitle: "IoT सेंसर टेलीमेट्री और फ़ील्ड नोड्स",
    monitoringDesc: "LoRaWAN फ़ील्ड प्रोब, मिट्टी सेंसर और मौसम नोड्स से लाइव डेटा।",
    simulatedSensors: "सिमुलेटेड सेंसर",
    hardwareGateway: "हार्डवेयर LoRa गेटवे",
    multiSensorTelemetry: "बहु-सेंसर टेलीमेट्री",
    telemetryDesc: "तापमान, नमी और मिट्टी नमी सहसंबंध",

    // Advisor
    advisorTitle: "स्वायत्त कृषि सलाहकार",
    advisorDesc: "बहु-मोडल संकेतों का विश्लेषण करने वाला स्वायत्त इंजन।",
    todaysFarmBriefing: "आज की खेत संक्षिप्ति (06:00 AM)",
    rankedRecommendations: "श्रेणीबद्ध सिफ़ारिशें",
    recommendedAction: "अनुशंसित कार्रवाई:",
    signalInputs: "संकेत स्रोत",
    impact: "प्रभाव",
    acknowledgeAction: "कार्रवाई स्वीकार करें",
    acknowledged: "स्वीकार किया",
    priority: "प्राथमिकता",

    modelMetricsTitle: "मॉडल मूल्यांकन मेट्रिक्स",
    modelMetricsDesc: "PlantVillage डेटासेट पर प्रशिक्षित मुख्य फसल रोग पहचान मॉडल का प्रशिक्षण विश्लेषण।",
    modelArchitecture: "मॉडल आर्किटेक्चर",
    dataset: "डेटासेट",
    totalImages: "कुल छवियाँ",
    finalValAccuracy: "अंतिम सत्यापन सटीकता",
    trainingConfig: "प्रशिक्षण कॉन्फ़िगरेशन",
    lossTab: "हानि",
    f1Tab: "मैक्रो-F1",
    confusionTab: "भ्रम मैट्रिक्स",
    perClassTab: "प्रति-वर्ग",
    landingHeroBadge: "AI-संचालित बुद्धिमान कृषि मंच",
    landingHeroTitle: "बुद्धिमान फसल स्वास्थ्य और स्मार्ट कृषि",
    landingHeroDesc: "कृषि दृष्टि गहन शिक्षण, IoT मृदा जल विज्ञान, कृषि-मौसम मॉडल और स्वायत्त कृषि सलाह को एक एकीकृत पारिस्थितिकी तंत्र में जोड़ती है।",
    landingGetStarted: "निःशुल्क शुरू करें",
    landingSignIn: "साइन इन करें",
    landingGoToDashboard: "डैशबोर्ड पर जाएं",
    landingExploreModule: "मॉड्यूल देखें",
    landingFeaturesTitle: "संपूर्ण कृषि बुद्धिमत्ता पारिस्थितिकी तंत्र",
    landingFeaturesDesc: "प्लगेबल FastAPI बैकएंड और रिस्पॉन्सिव डिज़ाइन के साथ मॉड्यूलर कृषि मंच।",
    landingCtaTitle: "कृषि उत्पादकता बढ़ाने के लिए तैयार हैं?",
    landingCtaDesc: "हमारे प्रशिक्षित कंप्यूटर विज़न मॉडल का परीक्षण करें या बहु-मोडल कृषि सलाह देखें।",
    landingCreateAccount: "निःशुल्क खाता बनाएं",
    landingFooterTagline: "कृत्रिम बुद्धिमत्ता से किसानों को सशक्त बनाना",
    landingBackToTop: "ऊपर जाएं",
    landingIntelligentCrop: "बुद्धिमान फसल स्वास्थ्य मंच",
    advisorFallbackDesc: "तर्क इंजन आपके खेत सेंसर, मौसम पूर्वानुमान और फसल निदान इतिहास से बहु-मोडल संकेतों का विश्लेषण कर रहा है।",
    modelMetricsNav: "मॉडल मेट्रिक्स",
  },
  pa: {
    // Navigation
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    cropDiagnosis: "ਫ਼ਸਲ ਰੋਗ ਨਿਦਾਨ",
    cropRecommendation: "ਫ਼ਸਲ ਸਿਫ਼ਾਰਸ਼",
    smartIrrigation: "ਸਮਾਰਟ ਸਿੰਚਾਈ",
    weatherIntelligence: "ਮੌਸਮ ਜਾਣਕਾਰੀ",
    sustainabilityScore: "ਟਿਕਾਊ ਖੇਤੀ ਸਕੋਰ",
    farmMonitoring: "ਖੇਤ ਨਿਗਰਾਨੀ (IoT)",
    aiAssistant: "ਏਆਈ ਕਿਸਾਨ ਸਹਾਇਕ",
    farmAdvisor: "ਖੇਤੀ ਸਲਾਹਕਾਰ",
    settings: "ਸੈਟਿੰਗਾਂ",

    // Badges & Common Header
    activeStation: "ਸਰਗਰਮ ਸਟੇਸ਼ਨ",
    quickDiagnosis: "ਤੁਰੰਤ ਜਾਂਚ",
    stationName: "ਉੱਤਰੀ ਖੇਤੀ ਹੱਬ (ਹਰਿਆਣਾ)",
    plotInfo: "ਪਲਾਟ A (ਕਰਨਾਲ ਹੱਬ)",
    plotDetails: "4.2 ਹੈਕਟੇਅਰ • ਡ੍ਰਿੱਪ ਚਾਲੂ",
    smartAgri: "ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ",
    simulationMode: "ਸਿਮੂਲੇਸ਼ਨ ਮੋਡ",
    coreAi: "ਕੋਰ ਏਆਈ",
    agentic: "ਏਜੰਟਿਕ",

    // Smart Irrigation Page
    irrigationTitle: "ਸਮਾਰਟ ਸਿੰਚਾਈ ਅਤੇ ਮਿੱਟੀ ਨਮੀ",
    irrigationDesc: "ਸੈਂਸਰ-ਅਧਾਰਤ ਜੜ੍ਹਾਂ ਦੀ ਨਮੀ ਅਤੇ ਮੌਸਮ ਅਨੁਸਾਰ ਸਿੰਚਾਈ ਯੋਜਨਾ।",
    manualCycle: "ਮੈਨੂਅਲ ਸਿੰਚਾਈ ਚੱਕਰ ਚਲਾਓ",
    haltSolenoid: "ਸਿੰਚਾਈ ਰੋਕੋ",
    rootZoneMoisture: "ਜੜ੍ਹ ਖੇਤਰ ਨਮੀ",
    target: "ਟੀਚਾ",
    waterRequired: "ਲੋੜੀਂਦਾ ਪਾਣੀ",
    fieldCapacity: "ਖੇਤ ਦੀ ਸਮਰੱਥਾ ਲਈ",
    nextCycle: "ਅਗਲਾ ਗੇੜ",
    eveningDrip: "ਸ਼ਾਮ ਦੀ ਤੁਪਕਾ ਸਿੰਚਾਈ",
    valveStatus: "ਵਾਲਵ ਸਥਿਤੀ",
    valveRunning: "ਚਾਲੂ (ਤੁਪਕਾ)",
    valveStandby: "ਸਟੈਂਡਬਾਏ",
    soilMoistureGauge: "ਮਿੱਟੀ ਨਮੀ ਮੀਟਰ",
    capacitiveDepth: "20 ਸੈਂਟੀਮੀਟਰ ਡੂੰਘਾਈ ਤੇ ਸੈਂਸਰ",
    volumetricContent: "ਪਾਣੀ ਦੀ ਮਾਤਰਾ",
    underMoistureTitle: "ਲੋੜੀਂਦੀ ਨਮੀ ਤੋਂ ਘੱਟ",
    underMoistureDesc: "ਮਿੱਟੀ ਦੀ ਨਮੀ ਘੱਟ ਹੈ, ਸਿੰਚਾਈ ਕਰਨ ਦੀ ਸਲਾਹ ਦਿੱਤੀ ਜਾਂਦੀ ਹੈ।",
    moistureTrendTitle: "24-ਘੰਟੇ ਦਾ ਨਮੀ ਰੁਝਾਨ",
    moistureTrendDesc: "ਪ੍ਰਤੀ ਘੰਟਾ ਰੀਡਿੰਗ",
    moisturePercent: "ਨਮੀ %",
    targetMin: "ਘੱਟੋ-ਘੱਟ ਟੀਚਾ (45%)",

    // Recommendations Page
    recTitle: "ਸੂਝਵਾਨ ਫ਼ਸਲ ਸਿਫ਼ਾਰਸ਼",
    recDesc: "ਮਿੱਟੀ ਦੇ ਪੋਸ਼ਕ ਤੱਤਾਂ ਅਤੇ ਜਲਵਾਯੂ ਸਥਿਤੀਆਂ ਦੇ ਆਧਾਰ ਤੇ ਏਆਈ ਦੁਆਰਾ ਸਭ ਤੋਂ ਢੁਕਵੀਆਂ ਫ਼ਸਲਾਂ ਪ੍ਰਾਪਤ ਕਰੋ।",
    soilParamsTitle: "ਮਿੱਟੀ ਅਤੇ ਜਲਵਾਯੂ ਮਾਪਦੰਡ",
    soilType: "ਮਿੱਟੀ ਦੀ ਕਿਸਮ",
    loamySoil: "ਦੋਮਟ ਮਿੱਟੀ (ਸੰਤੁਲਿਤ)",
    clayeyLoam: "ਚੀਕਣੀ ਦੋਮਟ ਮਿੱਟੀ",
    sandyLoam: "ਰੇਤਲੀ ਦੋਮਟ ਮਿੱਟੀ",
    blackCotton: "ਕਾਲੀ ਕਪਾਹ ਮਿੱਟੀ",
    nitrogen: "ਨਾਈਟ੍ਰੋਜਨ (N)",
    phosphorus: "ਫਾਸਫੋਰਸ (P)",
    potassium: "ਪੋਟਾਸ਼ੀਅਮ (K)",
    soilPh: "ਮਿੱਟੀ ਦਾ pH",
    temp: "ਤਾਪਮਾਨ (°C)",
    humidity: "ਨਮੀ (%)",
    rainfall: "ਮੀਂਹ (ਮਿਮੀ)",
    calcBtn: "ਸਿਫਾਰਸ਼ ਕੀਤੀਆਂ ਫ਼ਸਲਾਂ ਜਾਣੋ",
    evaluatingBtn: "ਮੁਲਾਂਕਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    awaitingTitle: "ਮਿੱਟੀ ਦੇ ਮੁਲਾਂਕਣ ਦੀ ਉਡੀਕ ਹੈ",
    awaitingDesc: "ਖੱਬੇ ਪਾਸੇ ਆਪਣੇ ਖੇਤ ਦੇ ਮੁੱਲ ਚੁਣੋ ਅਤੇ ਨਤੀਜੇ ਦੇਖੋ।",
    projectedYield: "ਅਨੁਮਾਨਿਤ ਝਾੜ",
    suitability: "ਢੁਕਵਾਂਪਣ",
    waterReq: "ਪਾਣੀ ਦੀ ਲੋੜ",
    growthCycle: "ਸਮਾਂ",
    days: "ਦਿਨ",
    sustainabilityRating: "ਸਥਿਰਤਾ ਰੇਟਿੰਗ",

    // Diagnosis Page
    diagnosisTitle: "ਏਆਈ ਫ਼ਸਲ ਰੋਗ ਨਿਦਾਨ",
    diagnosisDesc: "ਪੱਤੇ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ ਅਤੇ ਇਲਾਜ ਪ੍ਰਾਪਤ ਕਰੋ।",
    diagnosisHistory: "ਨਿਦਾਨ ਇਤਿਹਾਸ",
    scanLeafBtn: "ਪੱਤਾ ਸਕੈਨ ਕਰੋ",

    // Dashboard Page
    dashboardTitle: "ਕਰਨਾਲ ਪ੍ਰਿਸਿਜ਼ਨ ਐਗਰੋ-ਹੱਬ",
    dashboardDesc: "ਖੇਤੀਬਾੜੀ ਦੇ ਸਮੁੱਚੇ ਕੰਮਾਂ ਦਾ ਕੇਂਦਰ।",
    overallCropHealth: "ਕੁੱਲ ਫ਼ਸਲ ਸਿਹਤ",
    foliageIntegrity: "ਪਲਾਟ A ਪੱਤੇ ਦੀ ਸਥਿਤੀ",
    activeDiseaseAlerts: "ਸਰਗਰਮ ਰੋਗ ਚੇਤਾਵਨੀਆਂ",

    // Settings Page
    settingsTitle: "ਖੇਤ ਤਰਜੀਹਾਂ ਅਤੇ ਸੰਰਚਨਾ",
    settingsDesc: "ਜ਼ਮੀਨ ਦਾ ਖੇਤਰਫਲ, ਸਥਾਨਕ ਜਲਵਾਯੂ, ਇਕਾਈਆਂ ਅਤੇ ਬਹੁ-ਭਾਸ਼ਾਈ ਸੇਵਾਵਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ।",
    farmerProfile: "ਕਿਸਾਨ ਅਤੇ ਪਲਾਟ ਪ੍ਰੋਫਾਈਲ",
    farmerName: "ਕਿਸਾਨ ਦਾ ਨਾਮ",
    contactPhone: "ਸੰਪਰਕ ਨੰਬਰ",
    farmHolding: "ਖੇਤ ਦਾ ਨਾਮ",
    locationCoords: "ਸਥਾਨ",
    multilingual: "ਬਹੁ-ਭਾਸ਼ਾਈ ਅਤੇ ਯੂਨਿਟ",
    appLanguage: "ਐਪਲੀਕੇਸ਼ਨ ਭਾਸ਼ਾ",
    areaUnits: "ਖੇਤਰਫਲ ਇਕਾਈਆਂ",
    realtimeAlerts: "ਰੀਅਲ-ਟਾਈਮ ਚੇਤਾਵਨੀਆਂ",
    diseaseAlerts: "ਫ਼ਸਲ ਰੋਗ ਚੇਤਾਵਨੀਆਂ",
    diseaseAlertsDesc: "ਜਦੋਂ ਗੁਆਂਢੀ ਖੇਤਾਂ ਵਿੱਚ ਫੰਗਸ ਜਾਂ ਬਿਮਾਰੀ ਦਾ ਖਤਰਾ ਹੋਵੇ ਤਾਂ ਤੁਰੰਤ ਸੁਚੇਤ ਕਰੋ।",
    weatherAlerts: "ਮੀਂਹ ਅਤੇ ਕੋਹਰਾ ਚੇਤਾਵਨੀ",
    weatherAlertsDesc: "ਸਿੰਚਾਈ ਜਾਂ ਕੀਟਨਾਸ਼ਕ ਸਪਰੇਅ ਮੁਲਤਵੀ ਕਰਨ ਦੀ ਸਲਾਹ।",
    saveSettings: "ਸੈਟਿੰਗਾਂ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    savingSettings: "ਸੁਰੱਖਿਅਤ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    savedSuccess: "ਸਫਲਤਾਪੂਰਵਕ ਸੁਰੱਖਿਅਤ ਕੀਤਾ ਗਿਆ!",
    settingsPersisted: "ਸੈਟਿੰਗਾਂ ਸੁਰੱਖਿਅਤ ਕੀਤੀਆਂ ਗਈਆਂ ਹਨ।",

    // Quick Actions / Prompts
    analyzeCrop: "ਫ਼ਸਲ ਦੀ ਜਾਂਚ ਕਰੋ",
    explorePlatform: "ਖੇਤੀ ਦ੍ਰਿਸ਼ਟੀ ਵੇਖੋ",
    scanCropLeaf: "ਪੱਤਾ ਸਕੈਨ ਕਰੋ",
    recentFoliageInspections: "ਹਾਲੀਆ ਪੱਤੇ ਜਾਂਚ",
    fullAuditHistory: "ਪੂਰਾ ਇਤਿਹਾਸ",
    todaysBriefing: "ਅੱਜ ਦੀ ਖੇਤੀ ਸਲਾਹ",
    viewAllSignals: "ਸਾਰੇ ਸੰਕੇਤ ਵੇਖੋ",
    microclimatRisk: "ਸੂਖ੍ਸਮ ਜਲਵਾਯੂ ਖਤਰਾ",
    fullRadar: "ਪੂਰਾ ਰੇਡਾਰ",
    currentTemp: "ਮੌਜੂਦਾ ਤਾਪਮਾਨ",
    airHumidity: "ਹਵਾ ਨਮੀ",
    pathogenRisk: "ਰੋਗਾਣੂ ਖਤਰਾ",
    soilMoisture: "ਮਿੱਟੀ ਨਮੀ",
    sustainabilityRating2: "ਸਥਿਰਤਾ ਰੇਟਿੰਗ",
    coreModule: "ਮੁੱਖ ਮਾਡਿਊਲ",
    irrigationIntelligence: "ਸਮਾਰਟ ਸਿੰਚਾਈ ਪ੍ਰਣਾਲੀ",
    irrigationIntelligenceDesc: "ਰੀਅਲ-ਟਾਈਮ ਸੈਂਸਰ ਡੇਟਾ ਅਤੇ ਮੌਸਮ-ਸਚੇਤ ਸ਼ੈਡਿਊਲਿੰਗ ਨਾਲ ਸਟੀਕ ਮਿੱਟੀ ਨਮੀ ਪ੍ਰਬੰਧਨ।",
    cropGrowthStage: "ਫ਼ਸਲ ਵਿਕਾਸ ਪੌੜਾ",
    stageThresholdNote: "ਪੌੜੇ ਅਨੁਸਾਰ ਸੀਮਾ ਬਦਲਦੀ ਹੈ",
    rainDeferNotice: "ਮਿਮੀ ਮੀਂਹ ਦਾ ਅਨੁਮਾਨ — ਸਿੰਚਾਈ ਸਵੈਚਾਲਿਕ ਮੁਲਤਵੀ ਕੀਤੀ ਗਈ।",
    belowThreshold: "ਸੀਮਾ ਤੋਂ ਘੱਟ",
    moistureOptimal: "ਨਮੀ ਉਚਿਤ",
    moistureTrend: "ਨਮੀ ਰੁਝਾਨ",
    lastReadings: "ਆਖਰੀ 6 ਰੀਡਿੰਗਾਂ · 10 ਮਿੰਟ ਅੰਤਰਾਲ",
    refresh: "ਤਾਜ਼ਾ ਕਰੋ",
    weatherTitle: "ਖੇਤੀ ਮੌਸਮ ਵਿਗਿਆਨ ਅਤੇ ਰੋਗ ਖਤਰਾ",
    weatherDesc: "ਫ਼ਸਲ ਰੋਗਾਣੂ ਗਤਿਸ਼ੀਲਤਾ ਅਤੇ ਵਾਸ਼ਪੀਕਰਨ ਦਰ ਅਨੁਸਾਰ ਸੂਖ੍ਸਮ ਜਲਵਾਯੂ ਪੂਰਵਾਨੁਮਾਨ।",
    detectingLocation: "ਸਥਾਨ ਲੱਭਿਆ ਜਾ ਰਿਹਾ ਹੈ...",
    useMyLocation: "ਮੇਰਾ ਸਥਾਨ ਵਰਤੋ",
    temperature: "ਤਾਪਮਾਨ",
    relativeHumidity: "ਸਾਪੇਖ ਨਮੀ",
    precipitation: "ਵਰਸਾ",
    next24h: "ਅਗਲੇ 24 ਘੰਟੇ",
    pathogenRiskIndex: "ਰੋਗਾਣੂ ਖਤਰਾ ਸੂਚਕਾੰਕ",
    fungalPressure: "ਫੰਗਲ ਦਬਾਅ",
    agronomicAdvisories: "ਖੇਤੀ ਮੌਸਮ ਸਲਾਹ",
    fiveDayOutlook: "5-ਦਿਨੀ ਮੌਸਮ ਅਤੇ ਮੀਂਹ ਸੰਭਾਵਨਾ",
    locationDenied: "ਸਥਾਨ ਅਨੁਮਤੀ ਨਾਮੰਜ਼ੂਰ ਕੀਤੀ ਗਈ। ਡਿਫ਼ਾਲਟ ਸਥਾਨ (ਕਰਨਾਲ, ਹਰਿਆਣਾ) ਦਾ ਮੌਸਮ ਦਿਖਾਇਆ ਜਾ ਰਿਹਾ ਹੈ।",
    sustainabilityTitle: "ਖੇਤ ਸਥਿਰਤਾ ਅਤੇ ESG ਸੂਚਕਾੰਕ",
    sustainabilityDesc: "ਅਸਲ ਸੰਸਾਧਨ ਵਰਤੋਂ ਦਰਜ ਕਰੋ ਅਤੇ ਲਾਇਵ ਸਥਿਰਤਾ ਸਕੋਰ ਪ੍ਰਾਪਤ ਕਰੋ।",
    resourceUsageInputs: "ਸੰਸਾਧਨ ਵਰਤੋਂ ਇਨਪੁਟ",
    waterUsed: "ਵਰਤਿਆ ਪਾਣੀ (ਲੀਟਰ)",
    optimalWater: "ਸਰਵੋਤਮ ਪਾਣੀ (ਲੀਟਰ)",
    fertilizerUsed: "ਵਰਤਿਆ ਖਾਦ (kg)",
    recommendedDose: "ਸਿਫ਼ਾਰਸ਼ ਮਾਤਰਾ (kg)",
    cropHealthLive: "ਫ਼ਸਲ ਸਿਹਤ IoT ਸੈਂਸਰ ਤੋਂ ਲਾਇਵ ਲਈ ਜਾਂਦੀ ਹੈ।",
    calculateScore: "ਸਕੋਰ ਗਣੋ",
    calculating: "ਗਣਨਾ ਹੋ ਰਿਹਾ ਹੈ...",
    awaitingInputTitle: "ਇਨਪੁਟ ਦੀ ਉਡੀਕ",
    awaitingInputDesc: "ਖੱਬੇ ਪਾਸੇ ਪਾਣੀ ਅਤੇ ਖਾਦ ਦਰਜ ਕਰੋ, ਫਿਰ ਸਕੋਰ ਗਣੋ ਤੇ ਕਲਿੱਕ ਕਰੋ।",
    overallEcoRating: "ਸਮੁੱਚੀ ਪਾਰਿਸਥਿਤੀ ਖੇਤ ਰੇਟਿੰਗ",
    waterSaved: "ਬਚਾਇਆ ਪਾਣੀ",
    carbonOffset: "ਕਾਰਬਨ ਆਫਸੈਟ ਅਨੁਮਾਨ",
    vsYourUsage: "ਤੁਹਾਡੇ ਵਰਤੋਂ ਤੋਂ",
    co2Equivalent: "CO₂ ਸਮਤੁਲ",
    monitoringTitle: "IoT ਸੈਂਸਰ ਟੇਲੀਮੈਟ੍ਰੀ ਅਤੇ ਫੀਲਡ ਨੋਡਸ",
    monitoringDesc: "LoRaWAN ਫੀਲਡ ਪ੍ਰੋਬ, ਮਿੱਟੀ ਸੈਂਸਰ ਅਤੇ ਮੌਸਮ ਨੋਡਸ ਤੋਂ ਲਾਇਵ ਡੇਟਾ।",
    simulatedSensors: "ਸਿਮੂਲੇਟੇਡ ਸੈਂਸਰ",
    hardwareGateway: "ਹਾਰਡਵੇਅਰ LoRa ਗੇਟਵੇ",
    multiSensorTelemetry: "ਬਹੁ-ਸੈਂਸਰ ਟੇਲੀਮੈਟ੍ਰੀ",
    telemetryDesc: "ਤਾਪਮਾਨ, ਨਮੀ ਅਤੇ ਮਿੱਟੀ ਨਮੀ ਸੰਬੰਧ",
    advisorTitle: "ਸਵੈਚਾਲਿਕ ਖੇਤੀ ਸਲਾਹਕਾਰ",
    advisorDesc: "ਬਹੁ-ਮੋਡਲ ਸੰਕੇਤਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਨ ਵਾਲਾ ਸਵੈਚਾਲਿਕ ਇੰਜਣ।",
    todaysFarmBriefing: "ਅੱਜ ਦੀ ਖੇਤ ਸੰਖੇਪ (06:00 AM)",
    rankedRecommendations: "ਸ਼੍ਰੇਣੀਬੱਦ੍ਧ ਸਿਫ਼ਾਰਸ਼ਾਂ",
    recommendedAction: "ਸਿਫ਼ਾਰਸ਼ ਕਾਰਵਾਈ:",
    signalInputs: "ਸੰਕੇਤ ਸ੍ਰੋਤ",
    impact: "ਪ੍ਰਭਾਵ",
    acknowledgeAction: "ਕਾਰਵਾਈ ਸਵੀਕਾਰ ਕਰੋ",
    acknowledged: "ਸਵੀਕਾਰ ਕੀਤਾ",
    priority: "ਪ੍ਰਾਥਮਿਕਤਾ",

    modelMetricsTitle: "ਮੌਡਲ ਮੁਲਾਂਕਣ ਮੈਟ੍ਰਿਕਸ",
    modelMetricsDesc: "PlantVillage ਡੇਟਾਸੈੱਟ ਤੇ ਸਿਖਲਾਈ ਪ੍ਰਾਪਤ ਮੁੱਖ ਫ਼ਸਲ ਰੋਗ ਪਛਾਣ ਮੌਡਲ ਦਾ ਸਿਖਲਾਈ ਵਿਸ਼ਲੇਸ਼ਣ।",
    modelArchitecture: "ਮੌਡਲ ਢਾਂਚਾ",
    dataset: "ਡੇਟਾਸੈੱਟ",
    totalImages: "ਕੁੱਲ ਤਸਵੀਰਾਂ",
    finalValAccuracy: "ਅੰਤਿਮ ਸਤਾਪਨ ਸਟੀਕਤਾ",
    trainingConfig: "ਸਿਖਲਾਈ ਸੰਰਚਨਾ",
    lossTab: "ਨੁਕਸਾਨ",
    f1Tab: "ਮੈਕ੍ਰੋ-F1",
    confusionTab: "ਭੁਲੇਖੇ ਮੈਟ੍ਰਿਕਸ",
    perClassTab: "ਪ੍ਰਤੀ-ਸ਼੍ਰੇਣੀ",
    landingHeroBadge: "AI-ਸੰਚਾਲਿਤ ਸੁਝਾਵਾਂ ਖੇਤੀਬਾੜੀ ਮੰਚ",
    landingHeroTitle: "ਸੁਝਾਵਾਂ ਫ਼ਸਲ ਸਿਹਤ ਅਤੇ ਸਮਾਰਟ ਖੇਤੀ",
    landingHeroDesc: "ਕ੍ਰਿਸ਼ੀ ਦ੍ਰਿਸ਼ਟੀ ਗਹਿਰਾਈ ਸਿਖਲਾਈ, IoT ਮਿੱਟੀ ਜਲ ਵਿਗਿਆਨ, ਖੇਤੀ-ਮੌਸਮ ਮੌਡਲ ਅਤੇ ਸਵੈਚਾਲਿਕ ਖੇਤੀ ਸਲਾਹ ਨੂੰ ਇੱਕ ਸੰਯੁਕਤ ਤੰਤਰ ਵਿੱਚ ਜੋੜਦੀ ਹੈ।",
    landingGetStarted: "ਮੁਫ਼ਤ ਸ਼ੁਰੂ ਕਰੋ",
    landingSignIn: "ਸਾਈਨ ਇਨ ਕਰੋ",
    landingGoToDashboard: "ਡੈਸ਼ਬੋਰਡ ਤੇ ਜਾਓ",
    landingExploreModule: "ਮੌਡਿਊਲ ਵੇਖੋ",
    landingFeaturesTitle: "ਸੰਪੂਰਨ ਖੇਤੀਬਾੜੀ ਬੁੱਧੀਮਤਾ ਤੰਤਰ",
    landingFeaturesDesc: "ਪਲੱਗੇਬਲ FastAPI ਅਤੇ ਰਿਸਪਾਂਸਿਵ ਡਿਜ਼ਾਈਨ ਨਾਲ ਮੌਡਿਊਲਰ ਖੇਤੀ ਮੰਚ।",
    landingCtaTitle: "ਖੇਤੀਬਾੜੀ ਉਤਪਾਦਕਤਾ ਵਧਾਉਣ ਲਈ ਤਿਆਰ ਹੋ?",
    landingCtaDesc: "ਸਾਡੇ ਸਿਖਲਾਏ ਮੌਡਲ ਦੀ ਜਾਂਚ ਕਰੋ ਜਾਂ ਬਹੁ-ਮੌਡਲ ਖੇਤੀ ਸਲਾਹ ਵੇਖੋ।",
    landingCreateAccount: "ਮੁਫ਼ਤ ਖਾਤਾ ਬਣਾਓ",
    landingFooterTagline: "ਕ੍ਰਿਤ੍ਰਿਮ ਬੁੱਧੀਮਤਾ ਨਾਲ ਕਿਸਾਨਾਂ ਨੂੰ ਸ਼ਕਤੀਸ਼ਾਲੀ ਬਣਾਓ",
    landingBackToTop: "ਉੱਪਰ ਜਾਓ",
    landingIntelligentCrop: "ਸੁਝਾਵਾਂ ਫ਼ਸਲ ਸਿਹਤ ਮੰਚ",
    advisorFallbackDesc: "ਤਰਕ ਇੰਜਣ ਤੁਹਾਡੇ ਖੇਤ ਸੈਂਸਰ, ਮੌਸਮ ਪੂਰਵਾਨੁਮਾਨ ਅਤੇ ਫ਼ਸਲ ਨਿਦਾਨ ਇਤਿਹਾਸ ਤੋਂ ਬਹੁ-ਮੌਡਲ ਸੰਕੇਤਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹੈ।",
    modelMetricsNav: "ਮੌਡਲ ਮੈਟ੍ਰਿਕਸ",
  },
  te: {
    // Navigation
    dashboard: "డాష్‌బోర్డ్",
    cropDiagnosis: "పంట వ్యాధి నిర్ధారణ",
    cropRecommendation: "పంట సిఫార్సులు",
    smartIrrigation: "స్మార్ట్ నీటిపారుదల",
    weatherIntelligence: "వాతావరణ సమాచారం",
    sustainabilityScore: "సుస్థిర వ్యవసాయ స్కోరు",
    farmMonitoring: "పొలం పర్యవేక్షణ (IoT)",
    aiAssistant: "ఏఐ రైతు సహాయకుడు",
    farmAdvisor: "వ్యవసాయ సలహాదారు",
    settings: "సెట్టింగ్‌లు",

    // Badges & Common Header
    activeStation: "యాక్టివ్ స్టేషన్",
    quickDiagnosis: "త్వరిత నిర్ధారణ",
    stationName: "ఉత్తర వ్యవసాయ కేంద్రం (హర్యానా)",
    plotInfo: "ప్లాట్ A (కర్నాల్ హబ్)",
    plotDetails: "4.2 హెక్టార్లు • డ్రిప్ యాక్టివ్",
    smartAgri: "స్మార్ట్ వ్యవసాయం",
    simulationMode: "సిమ్యులేషన్ మోడ్",
    coreAi: "కోర్ ఏఐ",
    agentic: "ఏజెంటిక్",

    // Smart Irrigation Page
    irrigationTitle: "స్మార్ట్ నీటిపారుదల & నేల తేమ నిర్వహణ",
    irrigationDesc: "సెన్సార్ ఆధారిత తేమ విశ్లేషణ మరియు నీటి సరఫరా షెడ్యూల్.",
    manualCycle: "మాన్యువల్ సైకిల్ ప్రారంభించండి",
    haltSolenoid: "నీటి ప్రవాహాన్ని ఆపండి",
    rootZoneMoisture: "వేరు మండలంలో తేమ",
    target: "లక్ష్యం",
    waterRequired: "అవసరమైన నీరు",
    fieldCapacity: "ఫీల్డ్ సామర్థ్యం కోసం",
    nextCycle: "తదుపరి సైకిల్",
    eveningDrip: "సాయంత్రం డ్రిప్ స్లాట్",
    valveStatus: "వాల్వ్ స్థితి",
    valveRunning: "రన్నింగ్ (డ్రిప్)",
    valveStandby: "స్టాండ్‌బై",
    soilMoistureGauge: "నేల తేమ గేజ్",
    capacitiveDepth: "20 సెం.మీ లోతులో సెన్సార్ డేటా",
    volumetricContent: "నీటి శాతం",
    underMoistureTitle: "సిఫార్సు చేసిన దానికంటే తక్కువ తేమ",
    underMoistureDesc: "నేలలో తేమ తక్కువగా ఉంది, నీటిపారుదల అవసరం.",
    moistureTrendTitle: "24-గంటల నేల తేమ ట్రెండ్",
    moistureTrendDesc: "గంటవారీ రీడింగ్‌లు",
    moisturePercent: "తేమ %",
    targetMin: "కనిష్ట లక్ష్యం (45%)",

    // Recommendations Page
    recTitle: "స్మార్ట్ పంట సిఫార్సు విధానం",
    recDesc: "నేల రకం, వాతావరణం ఆధారంగా దిగుబడిని పెంచే పంటలను ఏఐ ద్వారా ఎంపిక చేసుకోండి.",
    soilParamsTitle: "నేల మరియు వాతావరణ పారామితులు",
    soilType: "నేల రకం",
    loamySoil: "ఒండ్రు నేల (సమతుల్య)",
    clayeyLoam: "బంకమట్టి ఒండ్రు",
    sandyLoam: "ఇసుక ఒండ్రు",
    blackCotton: "నల్లరేగడి నేల",
    nitrogen: "నైట్రోజన్ (N)",
    phosphorus: "భాస్వరం (P)",
    potassium: "పొటాషియం (K)",
    soilPh: "నేల pH",
    temp: "ఉష్ణోగ్రత (°C)",
    humidity: "తేమ శాతం (%)",
    rainfall: "వర్షపాతం (మి.మీ)",
    calcBtn: "సిఫార్సు చేయబడిన పంటలను లెక్కించండి",
    evaluatingBtn: "విశ్లేషణ జరుగుతోంది...",
    awaitingTitle: "నేల విశ్లేషణ కోసం వేచి ఉంది",
    awaitingDesc: "వివరాలను నమోదు చేసి పంటల జాబితాను పొందండి.",
    projectedYield: "అంచనా దిగుబడి",
    suitability: "అనుకూలత",
    waterReq: "నీటి అవసరం",
    growthCycle: "వ్యవధి",
    days: "రోజులు",
    sustainabilityRating: "స్థిరత్వ రేటింగ్",

    // Diagnosis Page
    diagnosisTitle: "ఏఐ పంట వ్యాధి గుర్తింపు",
    diagnosisDesc: "ఆకు ఫోటోను అప్‌లోడ్ చేసి వ్యాధి వివరాలను పొందండి.",
    diagnosisHistory: "నిర్ధారణ చరిత్ర",
    scanLeafBtn: "ఆకును స్కాన్ చేయండి",

    // Dashboard Page
    dashboardTitle: "కర్నాల్ ప్రెసిషన్ అగ్రో హబ్",
    dashboardDesc: "పంట ఆరోగ్యం మరియు సమాచార కేంద్రం.",
    overallCropHealth: "మొత్తం పంట ఆరోగ్యం",
    foliageIntegrity: "ప్లాట్ A ఆరోగ్యం",
    activeDiseaseAlerts: "సక్రియ వ్యాధి హెచ్చరికలు",

    // Settings Page
    settingsTitle: "వ్యవసాయ ప్రాధాన్యతలు & కాన్ఫిగరేషన్",
    settingsDesc: "భూమి విస్తీర్ణం, వాతావరణ సమాచారం, యూనిట్లు మరియు భాషలను నిర్వహించండి.",
    farmerProfile: "రైతు & ప్లాట్ ప్రొఫైల్",
    farmerName: "రైతు పేరు",
    contactPhone: "ఫోన్ నంబర్",
    farmHolding: "వ్యవసాయ క్షేత్రం పేరు",
    locationCoords: "ప్రాంతం వివరాలు",
    multilingual: "భాష & యూనిట్ల వివరాలు",
    appLanguage: "యాప్ భాష",
    areaUnits: "విస్తీర్ణ యూనిట్లు",
    realtimeAlerts: "వ్యవసాయ హెచ్చరికలు",
    diseaseAlerts: "కీలక పంట వ్యాధి హెచ్చరికలు",
    diseaseAlertsDesc: "వాతావరణం లేదా పొరుగు ప్రాంతాలలో తెగుళ్లు వ్యాపించే ప్రమాదం ఉన్నప్పుడు హెచ్చరికలు.",
    weatherAlerts: "వర్షం & మంచు హెచ్చరికలు",
    weatherAlertsDesc: "నీటిపారుదల లేదా మందుల పిచికారీ వాయిదా వేయడానికి సూచనలు.",
    saveSettings: "సెట్టింగ్‌లను సేవ్ చేయండి",
    savingSettings: "సేవ్ చేయబడుతోంది...",
    savedSuccess: "విజయవంతంగా సేవ్ చేయబడింది!",
    settingsPersisted: "సెట్టింగ్‌లు భద్రపరచబడ్డాయి.",

    // Quick Actions / Prompts
    analyzeCrop: "పంటను విశ్లేషించండి",
    explorePlatform: "వ్యవసాయ దర్శిని చూడండి",
    scanCropLeaf: "ఆకును స్కాన్ చేయండి",
    recentFoliageInspections: "తాజా ఆకు తనిఖీ",
    fullAuditHistory: "పూర్తి చరిత్ర",
    todaysBriefing: "నేటి వ్యవసాయ సలహా",
    viewAllSignals: "అన్ని సంకేతాలు చూడండి",
    microclimatRisk: "సూక్ష్మ వాతావరణ ప్రమాదం",
    fullRadar: "పూర్తి రాడార్",
    currentTemp: "ప్రస్తుత ఉష్ణోగ్రత",
    airHumidity: "గాలి తేమ",
    pathogenRisk: "రోగకారక ప్రమాదం",
    soilMoisture: "నేల తేమ",
    sustainabilityRating2: "స్థిరత్వ రేటింగ్",
    coreModule: "కోర్ మాడ్యూల్",
    irrigationIntelligence: "స్మార్ట్ నీటిపారుదల వ్యవస్థ",
    irrigationIntelligenceDesc: "రియల్-టైమ్ సెన్సార్ డేటా మరియు వర్షం-అవగాహన షెడ్యూలింగ్‌తో ఖచ్చితమైన నేల తేమ నిర్వహణ.",
    cropGrowthStage: "పంట వృద్ధి దశ",
    stageThresholdNote: "దశ ఆధారంగా పరిమితి మారుతుంది",
    rainDeferNotice: "మి.మీ వర్షం అంచనా — నీటిపారుదల స్వయంచాలకంగా వాయిదా వేయబడింది.",
    belowThreshold: "పరిమితి కంటే తక్కువ",
    moistureOptimal: "తేమ సరైనది",
    moistureTrend: "తేమ ట్రెండ్",
    lastReadings: "చివరి 6 రీడింగ్‌లు · 10 నిమిషాల వ్యవధి",
    refresh: "రిఫ్రెష్",
    weatherTitle: "వ్యవసాయ వాతావరణ విజ్ఞానం & వ్యాధి ప్రమాదం",
    weatherDesc: "పంట రోగకారక గతిశీలత మరియు బాష్పోత్సర్జన రేటు ఆధారంగా సూక్ష్మ వాతావరణ అంచనా.",
    detectingLocation: "స్థానం గుర్తిస్తోంది...",
    useMyLocation: "నా స్థానం వాడండి",
    temperature: "ఉష్ణోగ్రత",
    relativeHumidity: "సాపేక్ష తేమ",
    precipitation: "వర్షపాతం",
    next24h: "తదుపరి 24 గంటలు",
    pathogenRiskIndex: "రోగకారక ప్రమాద సూచిక",
    fungalPressure: "శిలీంధ్ర ఒత్తిడి",
    agronomicAdvisories: "వ్యవసాయ వాతావరణ సలహాలు",
    fiveDayOutlook: "5-రోజుల వాతావరణ & వర్షం సంభావ్యత",
    locationDenied: "స్థాన అనుమతి నిరాకరించబడింది. డిఫాల్ట్ స్థానం (కర్నాల్, హర్యానా) వాతావరణం చూపబడుతోంది.",
    sustainabilityTitle: "వ్యవసాయ స్థిరత్వం & ESG సూచికలు",
    sustainabilityDesc: "వాస్తవ వనరుల వినియోగం నమోదు చేసి లైవ్ స్థిరత్వ స్కోర్ పొందండి.",
    resourceUsageInputs: "వనరుల వినియోగ ఇన్‌పుట్",
    waterUsed: "వాడిన నీరు (లీటర్లు)",
    optimalWater: "సరైన నీరు (లీటర్లు)",
    fertilizerUsed: "వాడిన ఎరువు (kg)",
    recommendedDose: "సిఫార్సు మోతాదు (kg)",
    cropHealthLive: "పంట ఆరోగ్యం IoT సెన్సార్ నుండి లైవ్‌గా తీసుకోబడుతుంది.",
    calculateScore: "స్కోర్ లెక్కించండి",
    calculating: "లెక్కిస్తోంది...",
    awaitingInputTitle: "ఇన్‌పుట్ కోసం వేచి ఉంది",
    awaitingInputDesc: "ఎడమ వైపు నీరు మరియు ఎరువు నమోదు చేసి స్కోర్ లెక్కించండి.",
    overallEcoRating: "మొత్తం పర్యావరణ వ్యవసాయ రేటింగ్",
    waterSaved: "ఆదా చేసిన నీరు",
    carbonOffset: "కార్బన్ ఆఫ్‌సెట్ అంచనా",
    vsYourUsage: "మీ వినియోగంతో పోలిస్తే",
    co2Equivalent: "CO₂ సమానం",
    monitoringTitle: "IoT సెన్సార్ టెలిమెట్రీ & ఫీల్డ్ నోడ్స్",
    monitoringDesc: "LoRaWAN ఫీల్డ్ ప్రోబ్‌లు, నేల సెన్సార్లు మరియు వాతావరణ నోడ్‌ల నుండి లైవ్ డేటా.",
    simulatedSensors: "సిమ్యులేటెడ్ సెన్సార్లు",
    hardwareGateway: "హార్డ్‌వేర్ LoRa గేట్‌వే",
    multiSensorTelemetry: "బహు-సెన్సార్ టెలిమెట్రీ",
    telemetryDesc: "ఉష్ణోగ్రత, తేమ మరియు నేల తేమ సహసంబంధం",
    advisorTitle: "స్వయంచాలక వ్యవసాయ సలహాదారు",
    advisorDesc: "బహు-మోడల్ సంకేతాలను విశ్లేషించే స్వయంచాలక ఇంజిన్.",
    todaysFarmBriefing: "నేటి వ్యవసాయ సంక్షిప్తి (06:00 AM)",
    rankedRecommendations: "శ్రేణీకృత సిఫార్సులు",
    recommendedAction: "సిఫార్సు చేయబడిన చర్య:",
    signalInputs: "సంకేత మూలాలు",
    impact: "ప్రభావం",
    acknowledgeAction: "చర్యను అంగీకరించండి",
    acknowledged: "అంగీకరించబడింది",
    priority: "ప్రాధాన్యత",

    modelMetricsTitle: "మోడల్ మూల్యాంకన మెట్రిక్స్",
    modelMetricsDesc: "PlantVillage డేటాసెట్‌పై శిక్షణ పొందిన ప్రధాన పంట వ్యాధి గుర్తింపు మోడల్ శిక్షణ విశ్లేషణ.",
    modelArchitecture: "మోడల్ నిర్మాణం",
    dataset: "డేటాసెట్",
    totalImages: "మొత్తం చిత్రాలు",
    finalValAccuracy: "అంతిమ ధృవీకరణ ఖచ్చితత్వం",
    trainingConfig: "శిక్షణ కాన్ఫిగరేషన్",
    lossTab: "నష్టం",
    f1Tab: "మాక్రో-F1",
    confusionTab: "గందరగోళ మాతృక",
    perClassTab: "తరగతి వారీగా",
    landingHeroBadge: "AI-ఆధారిత తెలివైన వ్యవసాయ వేదిక",
    landingHeroTitle: "తెలివైన పంట ఆరోగ్యం & స్మార్ట్ వ్యవసాయం",
    landingHeroDesc: "కృషి దృష్టి లోతైన అభ్యాసం, IoT నేల జలవిజ్ఞానం, వ్యవసాయ-వాతావరణ నమూనాలు మరియు స్వయంచాలక వ్యవసాయ సలహాను ఒక్క వేదికలో కలుపుతుంది.",
    landingGetStarted: "ఉచితంగా ప్రారంభించండి",
    landingSignIn: "సైన్ ఇన్ చేయండి",
    landingGoToDashboard: "డాష్‌బోర్డ్‌కు వెళ్ళండి",
    landingExploreModule: "మాడ్యూల్ చూడండి",
    landingFeaturesTitle: "సంపూర్ణ వ్యవసాయ తెలివి పర్యావరణ వ్యవస్థ",
    landingFeaturesDesc: "ప్లగ్గబుల్ FastAPI మరియు రెస్పాన్సివ్ డిజైన్‌తో మాడ్యులర్ వ్యవసాయ వేదిక.",
    landingCtaTitle: "వ్యవసాయ ఉత్పాదకతను పెంచడానికి సిద్ధంగా ఉన్నారా?",
    landingCtaDesc: "మా శిక్షణ పొందిన మోడల్‌ను పరీక్షించండి లేదా బహు-మోడల్ వ్యవసాయ సలహాను చూడండి.",
    landingCreateAccount: "ఉచిత ఖాతా సృష్టించండి",
    landingFooterTagline: "కృత్రిమ మేధస్సుతో రైతులను సాధికారత చేయడం",
    landingBackToTop: "పైకి వెళ్ళండి",
    landingIntelligentCrop: "తెలివైన పంట ఆరోగ్య వేదిక",
    advisorFallbackDesc: "తర్క ఇంజిన్ మీ పొలం సెన్సార్లు, వాతావరణ అంచనా మరియు పంట నిర్ధారణ చరిత్ర నుండి బహు-మోడల్ సంకేతాలను విశ్లేషిస్తోంది.",
    modelMetricsNav: "మోడల్ మెట్రిక్స్",
  },
  gu: {
    dashboard: "ડેશબોર્ડ",
    cropDiagnosis: "પાક રોગ નિદાન",
    cropRecommendation: "પાક ભલામણ",
    smartIrrigation: "સ્માર્ટ સિંચાઈ",
    weatherIntelligence: "હવામાન માહિતી",
    sustainabilityScore: "ટકાઉ ખેતી સ્કોર",
    farmMonitoring: "ખેત દેખરેખ (IoT)",
    aiAssistant: "AI ખેડૂત સહાયક",
    farmAdvisor: "ખેતી સલાહકાર",
    settings: "સેટિંગ્સ",
    activeStation: "સક્રિય સ્ટેશન",
    quickDiagnosis: "ઝડપી તપાસ",
    stationName: "ઉત્તર કૃષિ કેન્દ્ર (હરિયાણા)",
    plotInfo: "પ્લોટ A (કરનાલ હબ)",
    plotDetails: "4.2 હેક્ટર • ડ્રિપ સક્રિય",
    smartAgri: "સ્માર્ટ ખેતી",
    simulationMode: "સિમ્યુલેશન મોડ",
    coreAi: "કોર AI",
    agentic: "એજન્ટિક",
    irrigationTitle: "સ્માર્ટ સિંચાઈ અને જમીન ભેજ વ્યવસ્થાપન",
    irrigationDesc: "સેન્સર-આધારિત મૂળ ઝોન ભેજ ટેલિમેટ્રી, બાષ્પોત્સર્જન મોડેલિંગ અને હવામાન-સુમેળ સિંચાઈ સમયપત્રક.",
    manualCycle: "મેન્યુઅલ સિંચાઈ ચક્ર શરૂ કરો",
    haltSolenoid: "સક્રિય સોલેનોઇડ બંધ કરો",
    rootZoneMoisture: "મૂળ ઝોન ભેજ",
    target: "લક્ષ્ય",
    waterRequired: "જરૂરી પાણી",
    fieldCapacity: "ખેત ક્ષમતા માટે",
    nextCycle: "આગળનું ચક્ર",
    eveningDrip: "સાંજની ડ્રિપ સ્લોટ",
    valveStatus: "વાલ્વ સ્થિતિ",
    valveRunning: "ચાલુ (ડ્રિપ)",
    valveStandby: "સ્ટેન્ડબાય",
    soilMoistureGauge: "જમીન ભેજ ગેજ",
    capacitiveDepth: "20 સે.મી. ઊંડાઈ પર સેન્સર ડેટા",
    volumetricContent: "પાણીનું પ્રમાણ",
    underMoistureTitle: "ભલામણ કરેલ ભેજ કરતાં ઓછું",
    underMoistureDesc: "જમીનનો ભેજ ઓછો છે, સિંચાઈ કરવાની સલાહ છે.",
    moistureTrendTitle: "24-કલાક જમીન ભેજ ટ્રેન્ડ",
    moistureTrendDesc: "કલાકદીઠ રીડિંગ",
    moisturePercent: "ભેજ %",
    targetMin: "લઘુત્તમ લક્ષ્ય (45%)",
    recTitle: "બુદ્ધિશાળી પાક ભલામણ",
    recDesc: "જમીનના પોષક તત્વો અને આબોહવા સ્થિતિ દાખલ કરો અને AI દ્વારા શ્રેષ્ઠ પાક મેળવો.",
    soilParamsTitle: "જમીન અને આબોહવા પ્રાચલ",
    soilType: "જમીનનો પ્રકાર",
    loamySoil: "ગોરાડુ જમીન (સંતુલિત)",
    clayeyLoam: "ચીકણી ગોરાડુ",
    sandyLoam: "રેતાળ ગોરાડુ",
    blackCotton: "કાળી કપાસ જમીન",
    nitrogen: "નાઇટ્રોજન (N)",
    phosphorus: "ફોસ્ફરસ (P)",
    potassium: "પોટેશિયમ (K)",
    soilPh: "જમીન pH",
    temp: "તાપમાન (°C)",
    humidity: "ભેજ (%)",
    rainfall: "વરસાદ (મિ.મી)",
    calcBtn: "ભલામણ કરેલ પાક ગણો",
    evaluatingBtn: "મૂલ્યાંકન થઈ રહ્યું છે...",
    awaitingTitle: "જમીન મૂલ્યાંકનની રાહ",
    awaitingDesc: "ડાબી બાજુ NPK અને આબોહવા મૂલ્યો સેટ કરો અને પરિણામ જુઓ.",
    projectedYield: "અંદાજિત ઉત્પાદન",
    suitability: "યોગ્યતા",
    waterReq: "પાણીની જરૂર",
    growthCycle: "સમયગાળો",
    days: "દિવસ",
    sustainabilityRating: "ટકાઉ રેટિંગ",
    diagnosisTitle: "AI પાક રોગ શોધ",
    diagnosisDesc: "પાંદડાની છબી અપલોડ કરો અને રોગ વિગતો મેળવો.",
    diagnosisHistory: "નિદાન ઇતિહાસ",
    scanLeafBtn: "પાંદડું સ્કેન કરો",
    dashboardTitle: "કરનાલ પ્રિસિઝન એગ્રો-હબ",
    dashboardDesc: "પાક આરોગ્ય અને માહિતી કેન્દ્ર.",
    overallCropHealth: "કુલ પાક આરોગ્ય",
    foliageIntegrity: "પ્લોટ A ની સ્થિતિ",
    activeDiseaseAlerts: "સક્રિય રોગ ચેતવણીઓ",
    settingsTitle: "ખેત પ્રાધાન્યતાઓ અને રૂપરેખા",
    settingsDesc: "જમીન વિસ્તાર, સ્થાનિક આબોહવા, એકમો અને બહુભાષી સેવાઓ સંચાલિત કરો.",
    farmerProfile: "ખેડૂત અને પ્લોટ પ્રોફાઇલ",
    farmerName: "ખેડૂતનું નામ",
    contactPhone: "સંપર્ક ફોન",
    farmHolding: "ખેતરનું નામ",
    locationCoords: "સ્થાન",
    multilingual: "બહુભાષી અને એકમ",
    appLanguage: "એપ્લિકેશન ભાષા",
    areaUnits: "વિસ્તાર એકમો",
    realtimeAlerts: "રીઅલ-ટાઇમ ચેતવણીઓ",
    diseaseAlerts: "પાક રોગ ચેતવણીઓ",
    diseaseAlertsDesc: "પડોશી ખેતરોમાં ફૂગ અથવા રોગ ફેલાવાનો ખતરો હોય ત્યારે ચેતવણી.",
    weatherAlerts: "વરસાદ અને હિમ ચેતવણી",
    weatherAlertsDesc: "સિંચાઈ અથવા જંતુનાશક છંટકાવ મોકૂફ રાખવાની સૂચના.",
    saveSettings: "સેટિંગ્સ સાચવો",
    savingSettings: "સાચવી રહ્યા છીએ...",
    savedSuccess: "સફળતાપૂર્વક સાચવ્યું!",
    settingsPersisted: "સેટિંગ્સ સુરક્ષિત રીતે સાચવ્યા.",
    analyzeCrop: "પાકની તપાસ કરો",
    explorePlatform: "કૃષિ દૃષ્ટિ જુઓ",
    scanCropLeaf: "પાંદડું સ્કેન કરો",
    recentFoliageInspections: "તાજેતરની પાંદડા તપાસ",
    fullAuditHistory: "પૂરો ઇતિહાસ",
    todaysBriefing: "આજની કૃષિ સલાહ",
    viewAllSignals: "બધા સંકેતો જુઓ",
    microclimatRisk: "સૂક્ષ્મ હવામાન જોખમ",
    fullRadar: "પૂરો રેડાર",
    currentTemp: "હાલનું તાપમાન",
    airHumidity: "હવાનો ભેજ",
    pathogenRisk: "રોગાણુ જોખમ",
    soilMoisture: "જમીન ભેજ",
    sustainabilityRating2: "ટકાઉ રેટિંગ",
    coreModule: "મુખ્ય મોડ્યુલ",
    irrigationIntelligence: "સ્માર્ટ સિંચાઈ પ્રણાલી",
    irrigationIntelligenceDesc: "રીઅલ-ટાઇમ સેન્સર ડેટા અને હવામાન-સચેત શેડ્યુલિંગ સાથે સચોટ જમીન ભેજ વ્યવસ્થાપન.",
    cropGrowthStage: "પાક વિકાસ તબક્કો",
    stageThresholdNote: "તબક્કા પ્રમાણે સીમા બદલાય છે",
    rainDeferNotice: "મિ.મી. વરસાદનું અનુમાન — સિંચાઈ આપોઆપ મોકૂફ કરાઈ.",
    belowThreshold: "સીમાથી ઓછું",
    moistureOptimal: "ભેજ યોગ્ય",
    moistureTrend: "ભેજ ટ્રેન્ડ",
    lastReadings: "છેલ્લી 6 રીડિંગ · 10 મિનિટ અંતરાલ",
    refresh: "તાજું કરો",
    weatherTitle: "કૃષિ હવામાન વિજ્ઞાન અને રોગ જોખમ",
    weatherDesc: "પાક રોગાણુ ગતિશીલતા અને બાષ્પોત્સર્જન દર પ્રમાણે સૂક્ષ્મ હવામાન પૂર્વાનુમાન.",
    detectingLocation: "સ્થાન શોધાઈ રહ્યું છે...",
    useMyLocation: "મારું સ્થાન વાપરો",
    temperature: "તાપમાન",
    relativeHumidity: "સાપેક્ષ ભેજ",
    precipitation: "વરસાદ",
    next24h: "આગળના 24 કલાક",
    pathogenRiskIndex: "રોગાણુ જોખમ સૂચકાંક",
    fungalPressure: "ફૂગી દબાણ",
    agronomicAdvisories: "કૃષિ હવામાન સલાહ",
    fiveDayOutlook: "5-દિવસીય હવામાન અને વરસાદ સંભાવના",
    locationDenied: "સ્થાન અનુમતિ નકારાઈ. ડિફોલ્ટ સ્થાન (કરનાલ, હરિયાણા) નું હવામાન દેખાડાઈ રહ્યું છે.",
    sustainabilityTitle: "ખેત ટકાઉપણું અને ESG સૂચકાંક",
    sustainabilityDesc: "વાસ્તવિક સંસાધન ઉપયોગ દાખલ કરો અને લાઇવ ટકાઉ સ્કોર મેળવો.",
    resourceUsageInputs: "સંસાધન ઉપયોગ ઇનપુટ",
    waterUsed: "વાપરેલું પાણી (લીટર)",
    optimalWater: "ઇષ્ટતમ પાણી (લીટર)",
    fertilizerUsed: "વાપરેલું ખાતર (kg)",
    recommendedDose: "ભલામણ માત્રા (kg)",
    cropHealthLive: "પાક આરોગ્ય IoT સેન્સરથી લાઇવ લેવાય છે.",
    calculateScore: "સ્કોર ગણો",
    calculating: "ગણતરી થઈ રહી છે...",
    awaitingInputTitle: "ઇનપુટની રાહ",
    awaitingInputDesc: "ડાબી બાજુ પાણી અને ખાતર દાખલ કરો, પછી સ્કોર ગણો પર ક્લિક કરો.",
    overallEcoRating: "સમગ્ર પારિસ્થિતિક ખેત રેટિંગ",
    waterSaved: "બચાવેલું પાણી",
    carbonOffset: "કાર્બન ઑફસેટ અંદાજ",
    vsYourUsage: "તમારા ઉપયોગ સામે",
    co2Equivalent: "CO₂ સમતુલ્ય",
    monitoringTitle: "IoT સેન્સર ટેલિમેટ્રી અને ફીલ્ડ નોડ્સ",
    monitoringDesc: "LoRaWAN ફીલ્ડ પ્રોબ, જમીન સેન્સર અને હવામાન નોડ્સથી લાઇવ ડેટા.",
    simulatedSensors: "સિમ્યુલેટેડ સેન્સર",
    hardwareGateway: "હાર્ડવેર LoRa ગેટવે",
    multiSensorTelemetry: "બહુ-સેન્સર ટેલિમેટ્રી",
    telemetryDesc: "તાપમાન, ભેજ અને જમીન ભેજ સંબંધ",
    advisorTitle: "સ્વાયત્ત કૃષિ સલાહકાર",
    advisorDesc: "બહુ-મોડલ સંકેતોનું વિશ્લેષણ કરતું સ્વાયત્ત ઇંજન.",
    todaysFarmBriefing: "આજની ખેત સંક્ષિપ્તિ (06:00 AM)",
    rankedRecommendations: "શ્રેણીબદ્ધ ભલામણો",
    recommendedAction: "ભલામણ કાર્યવાહી:",
    signalInputs: "સંકેત સ્રોત",
    impact: "પ્રભાવ",
    acknowledgeAction: "કાર્યવાહી સ્વીકારો",
    acknowledged: "સ્વીકારાયું",
    priority: "અગ્રતા",

    modelMetricsTitle: "મોડેલ મૂલ્યાંકન મેટ્રિક્સ",
    modelMetricsDesc: "PlantVillage ડેટાસેટ પર પ્રશિક્ષિત મુખ્ય પાક રોગ શોધ મોડેલનું પ્રશિક્ષણ વિશ્લેષણ.",
    modelArchitecture: "મોડેલ આર્કિટેક્ચર",
    dataset: "ડેટાસેટ",
    totalImages: "કુલ છબીઓ",
    finalValAccuracy: "અંતિમ ચકાસણી ચોકસાઈ",
    trainingConfig: "પ્રશિક્ષણ રૂપરેખા",
    lossTab: "નુકસાન",
    f1Tab: "મેક્રો-F1",
    confusionTab: "ગૂંચવણ મેટ્રિક્સ",
    perClassTab: "વર્ગ-દીઠ",
    landingHeroBadge: "AI-સંચાલિત બુદ્ધિશાળી કૃષિ મંચ",
    landingHeroTitle: "બુદ્ધિશાળી પાક આરોગ્ય અને સ્માર્ટ ખેતી",
    landingHeroDesc: "કૃષિ દૃષ્ટિ ઊંડા શિક્ષણ, IoT જમીન જળ વિજ્ઞાન, કૃષિ-હવામાન મોડેલ અને સ્વાયત્ત ખેતી સલાહને એક સંયુક્ત તંત્રમાં જોડે છે.",
    landingGetStarted: "મફત શરૂ કરો",
    landingSignIn: "સાઇન ઇન કરો",
    landingGoToDashboard: "ડેશબોર્ડ પર જાઓ",
    landingExploreModule: "મોડ્યુલ જુઓ",
    landingFeaturesTitle: "સંપૂર્ણ કૃષિ બુદ્ધિ પારિસ્થિતિક તંત્ર",
    landingFeaturesDesc: "પ્લગેબલ FastAPI અને રિસ્પોન્સિવ ડિઝાઇન સાથે મોડ્યુલર કૃષિ મંચ.",
    landingCtaTitle: "કૃષિ ઉત્પાદકતા વધારવા માટે તૈયાર છો?",
    landingCtaDesc: "અમારા પ્રશિક્ષિત મોડેલનું પરીક્ષણ કરો અથવા બહુ-મોડલ કૃષિ સલાહ જુઓ.",
    landingCreateAccount: "મફત ખાતું બનાવો",
    landingFooterTagline: "કૃત્રિમ બુદ્ધિ સાથે ખેડૂતોને સશક્ત બનાવવું",
    landingBackToTop: "ઉપર જાઓ",
    landingIntelligentCrop: "બુદ્ધિશાળી પાક આરોગ્ય મંચ",
    advisorFallbackDesc: "તર્ક ઇંજન તમારા ખેત સેન્સર, હવામાન પૂર્વાનુમાન અને પાક નિદાન ઇતિહાસ પરથી બહુ-મોડલ સંકેતોનું વિશ્લેષણ કરી રહ્યું છે.",
    modelMetricsNav: "મોડેલ મેટ્રિક્સ",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations["en"]) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => translations["en"][key] || key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    try {
      const saved = localStorage.getItem("krishidrishti_language");
      const validLangs = ["en", "hi", "pa", "te", "gu"];
      if (saved && validLangs.includes(saved)) {
        setLanguageState(saved as Language);
      } else {
        const settings = localStorage.getItem("krishidrishti_settings");
        if (settings) {
          const parsed = JSON.parse(settings);
          if (parsed.language && validLangs.includes(parsed.language)) {
            setLanguageState(parsed.language);
          }
        }
      }
    } catch (e) {
      console.error(e);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("krishidrishti_language", lang);
      const settings = localStorage.getItem("krishidrishti_settings");
      if (settings) {
        const parsed = JSON.parse(settings);
        parsed.language = lang;
        localStorage.setItem("krishidrishti_settings", JSON.stringify(parsed));
      }
    } catch (e) {
      console.error(e);
    }
  };

  const t = (key: keyof typeof translations["en"]): string => {
    const currentDict = translations[language] || translations["en"];
    return currentDict[key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
